/*-------------------------------------------------------------------------*
 *  Source Code:    %M%
 *-------------------------------------------------------------------------*
 *  Version:        %I%
 *  Version Date:   %G% - %U%
 *  Source Date:    %H% - %T%
 *
 *  Description:    Write product and pmfile to diskette.
 *
 *-------------------------------------------------------------------------*
 *                            Revision history                             |
 *-------------+-----------------------------------------------------------*
 * Change Date |            Author & Description                           |
 *-------------+-----------------------------------------------------------*
 *  10/26/93   |  tjt  Added to mfc.
 *  06/28/94   |  tjt  Revised for DOS diskettes.
 *  04/18/97   |  tjt  Add lanuage.h and code_ot_caps.
 *-------------------------------------------------------------------------*/
static char sku_diskette_write_c[] = "%Z% %M% %I% (%G% - %U%)";

/*************************************************************** 
 *   sku_diskette_write.c                                      *
 *                                                             *
 *   Creates ASCII formatted diskettes, one for SKU data and   *
 *   a second diskette for Pick Module data.                   *
 *                                                             *
 *   Input to this program are the pf_data and pm_data files   *
 *   generated by the "create_output_file" program.            *
 *                                                             *
 ***************************************************************/

#include <stdio.h>
#include "ss.h"
#include "file_names.h"
#include "eh_nos.h"
#include "iodefs.h"
#include "sd.h"
#include "language.h"

#define BUF_SIZE 2

short ONE = 1;

struct fld_parms fld = {22,58,25,1,&ONE,"Diskette Ready? (y/n)",'a'};


char pbuf[BUF_SIZE], yn[2];               /* prompt buffer                   */
char buf[128];                            /* Input buffer                    */
long ret,i;                               /* working variable                */
short rm;
unsigned char t;

char command[80];
main()
{
  extern close_all();

  putenv("_=sku_diskette_write");
  chdir(getenv("HOME"));

  ss_open();
  ss_close();
  
  sd_open(close_all);
  
/*------------------------------------------------------------------------*
 *   MAIN LOOP
 *------------------------------------------------------------------------*/

  while(1)
  {
                /* Write SKU Data to Diskette   */
    memset(yn, 0, 2);
    sd_cursor (0,20,25);
    sd_text ("Insert Diskette For SKU Output");
    t = sd_input(&fld,sd_prompt(&fld,0),&rm,yn,0);
    if (t == EXIT)
    {
      close_all();
      exit(0);
    }
    *pbuf = code_to_caps(*yn);
    if (*pbuf != 'y' && *pbuf != 'n')
    {
      eh_post(ERR_YN,0);
      continue;
    }
    sd_cursor(0,20,1);
    sd_clear_line();
    sd_cursor(0,22,1);
    sd_clear_line();

    if (*pbuf == 'n')
    {
      close_all();
      exit(0);
    }
    sprintf(command, "doscp %s A:PF.DAT", pf_data_name);
    ret = system(command);
    if (ret)
    {
      close_all();
      exit(1);
    }
                /* Write Pick Module Data to Diskette   */

    i = 0;                                /* initialize record count         */
    sd_cursor (0,20,25);
    sd_text ("Remove SKU Diskette");
    sd_cursor (0,21,25);
    sd_text ("Insert Diskette For Pick Module Output");
    memset(yn, 0, 2);
    t = sd_input(&fld,sd_prompt(&fld,0),&rm,yn,0);
    if (t == EXIT)
    {
      close_all();
      exit(0);
    }
    *pbuf = code_to_caps(*yn);
    if (*pbuf != 'y' && *pbuf != 'n')
    {
      eh_post(ERR_YN,0);
      continue;
    }
    clear_screen();
    if (*pbuf == 'n')
    {
      close_all();
      exit(0);
    }
    sprintf(command, "doscp %s A:PM.DAT", pm_data_name);
    ret = system(command);
    if (ret)
    {
      close_all();
      exit(2);
    }
    close_all();
    break;
  }
  exit(0);
}

/* close all files before returning to calling program  */

close_all()
{
  sd_close();
  return;
}
/* clear rows 20,21,22 on screen        */
clear_screen()
{
  sd_cursor (0,20,1);
  sd_clear_line();
  sd_cursor (0,21,1);
  sd_clear_line();
  sd_cursor (0,22,1);
  sd_clear_line();
  return;
}

/* end of sku_diskette_write.c */
